theme = "github_dark"
# theme = "dracula"

[editor]
# line-number = "relative"
mouse = false
# bufferline = "multiple"

[editor.cursor-shape]
insert = "bar"
# normal = "block"
# select = "block"

[editor.file-picker]
hidden = true
git-ignore = true
